### ISSUE TITLE
nRF52832_qfaa_dcdc.sch incorrectly lists C7 as 100nf

### ISSUE THREAD

**Issue by jacobrosenthal** [NordicSemiconductor/nrf5-eagle-reference-design#2]
In nRF52832_qfaa_dcdc.sch (and maybe others?) C7 is I believe incorrectly listed as 100nF as the nrf52832_qfaa_dcdc_bom.xls in the reference http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52%2Fdita%2Fnrf52%2Fpdflinks%2Fref_layout.html&cp=1_5 lists C7 as 100pF

**Comment by Cable89** [comment]
You are correct, thank you for pointing it out. I changed the value of C7 to 100pF in the schematics for all three nrf52 schematics.
