### ISSUE TITLE
DEBUG_CONNECTOR - wrong connection P0.21/RESET - 6 and P0.18/SWO - 10 ??

### ISSUE THREAD

**Issue by BrunoArgon18** [NordicSemiconductor/nrf5-eagle-reference-design#3]
Hi. i would like to know if the connection between P0.21/RESET - 6 and P0.18/SWO - 10  are correct.

I checked this document (PCA10040_Schematic_And_PCB.pdf) and they say that:

P0.21/RESET - 10 and P0.18/SWO - 6

There is the http://infocenter.arm.com/help/topic/com.arm.doc.faqs/attached/13634/cortex_debug_connectors.pdf

from ARM that say the same thing.

Tks

**Comment by Cable89** [comment]
You are correct, P0.21 should be connected to 10 and P0.18 to 6.
However you will still be able to debug as it is only SWDIO and SWDCLK wich are used during debugging. If reset is not present it will do a soft reset.

Thank you, it should be correct now.
