### ISSUE TITLE
Mislabeled NFC pin?

### ISSUE THREAD

**Issue by todeschini-felipe** [NordicSemiconductor/nrf5-eagle-reference-design#6]
Surely those are minor "issues", but I wanted to inquire about them (and give some "contribution") to ensure **nRF52832_qfaa_dcdc schematic** consistency with **nRF52832 Product Specification v 1.4 pg. 546 **.

1. I believe that P0.09 and P0.10 are mislabeled as P0.01 and P0.09, respectively.
2. Capacitor C1 and C2 labels seem to be inverted. 

I believe, nonetheless, that these things do not actually change the schematic "behavior".
Regards,

**Comment by Cable89** [comment]
Hi,
Thanks for the feedback. Even minor stuff like this may cause unnecessary confusion.

1. Fixed.
2. Swapped them.
