### ISSUE TITLE
nrf52840 refrerences show nrf52830

### ISSUE THREAD

**Issue by rsaxvc** [NordicSemiconductor/nrf5-eagle-reference-design#8]
All PDFs in https://github.com/NordicPlayground/nrf5-eagle-reference-design/tree/master/nRF52840_reference show nRF52832 instead of nRF52840. Example: https://github.com/NordicPlayground/nrf5-eagle-reference-design/blob/master/nRF52840_reference/nRF52840_qiaa_var1/nRF52840_qfaa_var1_sch.pdf

**Comment by Cable89** [comment]
Thanks, it seems I have forgotten to generate the pdfs for the nRF52840, and the old pdfs from nRF52832 has remained. I have now generated the correct pdfs.
